apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: tons/im-job
deploy:
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: im-job-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        artifactOverrides:
          image: tons/im-job
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/values.yaml
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml
