consumes:
- application/json
info:
  contact:
    email: info@dhis2.org
    url: https://github.com/dhis2-sre/im-job
  description: Database Manager Service as part of the Instance Manager environment
  license:
    name: TODO
  termsOfService: There are no TOS at this moment, use at your own risk we take no
    responsibility
  title: Instance Database Manager Service.
  version: 0.1.0
paths: {}
produces:
- application/json
responses:
  Error:
    description: ""
securityDefinitions:
  oauth2:
    flow: password
    tokenUrl: /not-valid--endpoint-is-served-from-the-im-user-service
    type: oauth2
swagger: "2.0"
