// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/dhis2-sre/im-job/internal/client"
	"github.com/dhis2-sre/im-job/internal/handler"
	"github.com/dhis2-sre/im-job/pkg/config"
	"github.com/dhis2-sre/im-job/pkg/job"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configConfig := config.ProvideConfig()
	authenticationMiddleware := handler.ProvideAuthentication(configConfig)
	clientClient := client.ProvideUser(configConfig)
	repository := job.ProvideRepository()
	kubernetesService := job.ProvideKubernetesService()
	service := job.ProvideService(configConfig, repository, kubernetesService)
	jobHandler := job.ProvideHandler(clientClient, service)
	environment := ProvideEnvironment(configConfig, authenticationMiddleware, jobHandler)
	return environment
}

// wire.go:

type Environment struct {
	Config                   config.Config
	AuthenticationMiddleware handler.AuthenticationMiddleware
	JobHandler               job.Handler
}

func ProvideEnvironment(config2 config.Config,

	authenticationMiddleware handler.AuthenticationMiddleware,
	jobHandler job.Handler,
) Environment {
	return Environment{config2, authenticationMiddleware,
		jobHandler,
	}
}
