// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/dhis2-sre/im-job/internal/handler"
	"github.com/dhis2-sre/im-job/pkg/config"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configConfig := config.ProvideConfig()
	authenticationMiddleware := handler.ProvideAuthentication(configConfig)
	environment := ProvideEnvironment(configConfig, authenticationMiddleware)
	return environment
}

// wire.go:

type Environment struct {
	Config                   config.Config
	AuthenticationMiddleware handler.AuthenticationMiddleware
}

func ProvideEnvironment(config2 config.Config,

	authenticationMiddleware handler.AuthenticationMiddleware,
) Environment {
	return Environment{config2, authenticationMiddleware}
}
