// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindJobParams creates a new FindJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindJobParams() *FindJobParams {
	return &FindJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindJobParamsWithTimeout creates a new FindJobParams object
// with the ability to set a timeout on a request.
func NewFindJobParamsWithTimeout(timeout time.Duration) *FindJobParams {
	return &FindJobParams{
		timeout: timeout,
	}
}

// NewFindJobParamsWithContext creates a new FindJobParams object
// with the ability to set a context for a request.
func NewFindJobParamsWithContext(ctx context.Context) *FindJobParams {
	return &FindJobParams{
		Context: ctx,
	}
}

// NewFindJobParamsWithHTTPClient creates a new FindJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindJobParamsWithHTTPClient(client *http.Client) *FindJobParams {
	return &FindJobParams{
		HTTPClient: client,
	}
}

/* FindJobParams contains all the parameters to send to the API endpoint
   for the find job operation.

   Typically these are written to a http.Request.
*/
type FindJobParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindJobParams) WithDefaults() *FindJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find job params
func (o *FindJobParams) WithTimeout(timeout time.Duration) *FindJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find job params
func (o *FindJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find job params
func (o *FindJobParams) WithContext(ctx context.Context) *FindJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find job params
func (o *FindJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find job params
func (o *FindJobParams) WithHTTPClient(client *http.Client) *FindJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find job params
func (o *FindJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find job params
func (o *FindJobParams) WithID(id uint64) *FindJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find job params
func (o *FindJobParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
