// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-job/swagger/sdk/models"
)

// JobStatusReader is a Reader for the JobStatus structure.
type JobStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewJobStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewJobStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewJobStatusForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewJobStatusUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobStatusOK creates a JobStatusOK with default headers values
func NewJobStatusOK() *JobStatusOK {
	return &JobStatusOK{}
}

/* JobStatusOK describes a response with status code 200, with default header values.

JobStatusOK job status o k
*/
type JobStatusOK struct {
	Payload *models.Job
}

func (o *JobStatusOK) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/status][%d] jobStatusOK  %+v", 200, o.Payload)
}
func (o *JobStatusOK) GetPayload() *models.Job {
	return o.Payload
}

func (o *JobStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobStatusBadRequest creates a JobStatusBadRequest with default headers values
func NewJobStatusBadRequest() *JobStatusBadRequest {
	return &JobStatusBadRequest{}
}

/* JobStatusBadRequest describes a response with status code 400, with default header values.

JobStatusBadRequest job status bad request
*/
type JobStatusBadRequest struct {
}

func (o *JobStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/status][%d] jobStatusBadRequest ", 400)
}

func (o *JobStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobStatusUnauthorized creates a JobStatusUnauthorized with default headers values
func NewJobStatusUnauthorized() *JobStatusUnauthorized {
	return &JobStatusUnauthorized{}
}

/* JobStatusUnauthorized describes a response with status code 401, with default header values.

JobStatusUnauthorized job status unauthorized
*/
type JobStatusUnauthorized struct {
}

func (o *JobStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/status][%d] jobStatusUnauthorized ", 401)
}

func (o *JobStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobStatusForbidden creates a JobStatusForbidden with default headers values
func NewJobStatusForbidden() *JobStatusForbidden {
	return &JobStatusForbidden{}
}

/* JobStatusForbidden describes a response with status code 403, with default header values.

JobStatusForbidden job status forbidden
*/
type JobStatusForbidden struct {
}

func (o *JobStatusForbidden) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/status][%d] jobStatusForbidden ", 403)
}

func (o *JobStatusForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobStatusUnsupportedMediaType creates a JobStatusUnsupportedMediaType with default headers values
func NewJobStatusUnsupportedMediaType() *JobStatusUnsupportedMediaType {
	return &JobStatusUnsupportedMediaType{}
}

/* JobStatusUnsupportedMediaType describes a response with status code 415, with default header values.

JobStatusUnsupportedMediaType job status unsupported media type
*/
type JobStatusUnsupportedMediaType struct {
}

func (o *JobStatusUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/status][%d] jobStatusUnsupportedMediaType ", 415)
}

func (o *JobStatusUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
