// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewJobStatusParams creates a new JobStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewJobStatusParams() *JobStatusParams {
	return &JobStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewJobStatusParamsWithTimeout creates a new JobStatusParams object
// with the ability to set a timeout on a request.
func NewJobStatusParamsWithTimeout(timeout time.Duration) *JobStatusParams {
	return &JobStatusParams{
		timeout: timeout,
	}
}

// NewJobStatusParamsWithContext creates a new JobStatusParams object
// with the ability to set a context for a request.
func NewJobStatusParamsWithContext(ctx context.Context) *JobStatusParams {
	return &JobStatusParams{
		Context: ctx,
	}
}

// NewJobStatusParamsWithHTTPClient creates a new JobStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewJobStatusParamsWithHTTPClient(client *http.Client) *JobStatusParams {
	return &JobStatusParams{
		HTTPClient: client,
	}
}

/* JobStatusParams contains all the parameters to send to the API endpoint
   for the job status operation.

   Typically these are written to a http.Request.
*/
type JobStatusParams struct {

	// RunID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the job status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobStatusParams) WithDefaults() *JobStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the job status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the job status params
func (o *JobStatusParams) WithTimeout(timeout time.Duration) *JobStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job status params
func (o *JobStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job status params
func (o *JobStatusParams) WithContext(ctx context.Context) *JobStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job status params
func (o *JobStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job status params
func (o *JobStatusParams) WithHTTPClient(client *http.Client) *JobStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job status params
func (o *JobStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the runID to the job status params
func (o *JobStatusParams) WithID(runID uint64) *JobStatusParams {
	o.SetID(runID)
	return o
}

// SetID adds the runId to the job status params
func (o *JobStatusParams) SetID(runID uint64) {
	o.ID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *JobStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param runId
	if err := r.SetPathParam("runId", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
