// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JobLogsReader is a Reader for the JobLogs structure.
type JobLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewJobLogsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewJobLogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewJobLogsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewJobLogsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobLogsOK creates a JobLogsOK with default headers values
func NewJobLogsOK() *JobLogsOK {
	return &JobLogsOK{}
}

/* JobLogsOK describes a response with status code 200, with default header values.

JobLogsOK job logs o k
*/
type JobLogsOK struct {
}

func (o *JobLogsOK) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/logs][%d] jobLogsOK ", 200)
}

func (o *JobLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobLogsBadRequest creates a JobLogsBadRequest with default headers values
func NewJobLogsBadRequest() *JobLogsBadRequest {
	return &JobLogsBadRequest{}
}

/* JobLogsBadRequest describes a response with status code 400, with default header values.

JobLogsBadRequest job logs bad request
*/
type JobLogsBadRequest struct {
}

func (o *JobLogsBadRequest) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/logs][%d] jobLogsBadRequest ", 400)
}

func (o *JobLogsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobLogsUnauthorized creates a JobLogsUnauthorized with default headers values
func NewJobLogsUnauthorized() *JobLogsUnauthorized {
	return &JobLogsUnauthorized{}
}

/* JobLogsUnauthorized describes a response with status code 401, with default header values.

JobLogsUnauthorized job logs unauthorized
*/
type JobLogsUnauthorized struct {
}

func (o *JobLogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/logs][%d] jobLogsUnauthorized ", 401)
}

func (o *JobLogsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobLogsForbidden creates a JobLogsForbidden with default headers values
func NewJobLogsForbidden() *JobLogsForbidden {
	return &JobLogsForbidden{}
}

/* JobLogsForbidden describes a response with status code 403, with default header values.

JobLogsForbidden job logs forbidden
*/
type JobLogsForbidden struct {
}

func (o *JobLogsForbidden) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/logs][%d] jobLogsForbidden ", 403)
}

func (o *JobLogsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJobLogsUnsupportedMediaType creates a JobLogsUnsupportedMediaType with default headers values
func NewJobLogsUnsupportedMediaType() *JobLogsUnsupportedMediaType {
	return &JobLogsUnsupportedMediaType{}
}

/* JobLogsUnsupportedMediaType describes a response with status code 415, with default header values.

JobLogsUnsupportedMediaType job logs unsupported media type
*/
type JobLogsUnsupportedMediaType struct {
}

func (o *JobLogsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /jobs/running/{runId}/logs][%d] jobLogsUnsupportedMediaType ", 415)
}

func (o *JobLogsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
