// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-job/swagger/sdk/models"
)

// RunJobReader is a Reader for the RunJob structure.
type RunJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRunJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRunJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRunJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRunJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewRunJobUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRunJobOK creates a RunJobOK with default headers values
func NewRunJobOK() *RunJobOK {
	return &RunJobOK{}
}

/* RunJobOK describes a response with status code 200, with default header values.

RunJobResponse
*/
type RunJobOK struct {
	Payload *models.RunJobResponse
}

func (o *RunJobOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{id}/run][%d] runJobOK  %+v", 200, o.Payload)
}
func (o *RunJobOK) GetPayload() *models.RunJobResponse {
	return o.Payload
}

func (o *RunJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunJobBadRequest creates a RunJobBadRequest with default headers values
func NewRunJobBadRequest() *RunJobBadRequest {
	return &RunJobBadRequest{}
}

/* RunJobBadRequest describes a response with status code 400, with default header values.

RunJobBadRequest run job bad request
*/
type RunJobBadRequest struct {
}

func (o *RunJobBadRequest) Error() string {
	return fmt.Sprintf("[GET /jobs/{id}/run][%d] runJobBadRequest ", 400)
}

func (o *RunJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunJobUnauthorized creates a RunJobUnauthorized with default headers values
func NewRunJobUnauthorized() *RunJobUnauthorized {
	return &RunJobUnauthorized{}
}

/* RunJobUnauthorized describes a response with status code 401, with default header values.

RunJobUnauthorized run job unauthorized
*/
type RunJobUnauthorized struct {
}

func (o *RunJobUnauthorized) Error() string {
	return fmt.Sprintf("[GET /jobs/{id}/run][%d] runJobUnauthorized ", 401)
}

func (o *RunJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunJobForbidden creates a RunJobForbidden with default headers values
func NewRunJobForbidden() *RunJobForbidden {
	return &RunJobForbidden{}
}

/* RunJobForbidden describes a response with status code 403, with default header values.

RunJobForbidden run job forbidden
*/
type RunJobForbidden struct {
}

func (o *RunJobForbidden) Error() string {
	return fmt.Sprintf("[GET /jobs/{id}/run][%d] runJobForbidden ", 403)
}

func (o *RunJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunJobUnsupportedMediaType creates a RunJobUnsupportedMediaType with default headers values
func NewRunJobUnsupportedMediaType() *RunJobUnsupportedMediaType {
	return &RunJobUnsupportedMediaType{}
}

/* RunJobUnsupportedMediaType describes a response with status code 415, with default header values.

RunJobUnsupportedMediaType run job unsupported media type
*/
type RunJobUnsupportedMediaType struct {
}

func (o *RunJobUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /jobs/{id}/run][%d] runJobUnsupportedMediaType ", 415)
}

func (o *RunJobUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
