// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/dhis2-sre/im-job/swagger/sdk/models"
)

// NewRunJobParams creates a new RunJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunJobParams() *RunJobParams {
	return &RunJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunJobParamsWithTimeout creates a new RunJobParams object
// with the ability to set a timeout on a request.
func NewRunJobParamsWithTimeout(timeout time.Duration) *RunJobParams {
	return &RunJobParams{
		timeout: timeout,
	}
}

// NewRunJobParamsWithContext creates a new RunJobParams object
// with the ability to set a context for a request.
func NewRunJobParamsWithContext(ctx context.Context) *RunJobParams {
	return &RunJobParams{
		Context: ctx,
	}
}

// NewRunJobParamsWithHTTPClient creates a new RunJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunJobParamsWithHTTPClient(client *http.Client) *RunJobParams {
	return &RunJobParams{
		HTTPClient: client,
	}
}

/* RunJobParams contains all the parameters to send to the API endpoint
   for the run job operation.

   Typically these are written to a http.Request.
*/
type RunJobParams struct {

	/* Body.

	   Run job request body parameter
	*/
	Body *models.RunJobRequest

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the run job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunJobParams) WithDefaults() *RunJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the run job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the run job params
func (o *RunJobParams) WithTimeout(timeout time.Duration) *RunJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the run job params
func (o *RunJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the run job params
func (o *RunJobParams) WithContext(ctx context.Context) *RunJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the run job params
func (o *RunJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the run job params
func (o *RunJobParams) WithHTTPClient(client *http.Client) *RunJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the run job params
func (o *RunJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the run job params
func (o *RunJobParams) WithBody(body *models.RunJobRequest) *RunJobParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the run job params
func (o *RunJobParams) SetBody(body *models.RunJobRequest) {
	o.Body = body
}

// WithID adds the id to the run job params
func (o *RunJobParams) WithID(id uint64) *RunJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the run job params
func (o *RunJobParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RunJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
