apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "im-job.fullname" . }}
  labels:
    {{- include "im-job.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
