{{- $root := . -}}
{{- $fullname := include "im-job.fullname" . }}

{{- range $namespace := split "," .Values.groups.names }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  namespace: {{ $namespace }}
  labels:
  {{- include "im-job.labels" $root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "im-job.serviceAccountName" $root }}
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $fullname }}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}
  namespace: {{ $namespace }}
  labels:
  {{- include "im-job.labels" $root | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
{{- end }}
