kind: Secret
apiVersion: v1
metadata:
  name: {{ include "im-job.fullname" . }}
  labels:
    {{- include "im-job.labels" . | nindent 4 }}
type: Opaque
data:
  DHIS2_DATABASE_USERNAME: {{ .Values.dhis2Database.username | b64enc }}
  DHIS2_DATABASE_PASSWORD: {{ .Values.dhis2Database.password | b64enc }}
  DHIS2_DATABASE_DATABASE: {{ .Values.dhis2Database.database | b64enc }}
